### ISSUE TITLE
UnboundLocalError exception in the + operator

### ISSUE THREAD

**Issue by aervnu** [GitHubCat-dev/python-calculator#1]
When the + operator is used, and a legitimate input is made in the 1st number input field but an illegitimate input is made in the 2nd number field, the `UnboundLocalError` exception is encountered. The app automatically terminates after this event.
![image_2021-11-18_083707](https://user-images.githubusercontent.com/70247964/142335289-5e624ec4-16ce-41d1-993a-e215b2ca9c42.png)
![image](https://user-images.githubusercontent.com/70247964/142335458-8338830f-3323-4fa2-acb6-5fbbabce6344.png)

**Comment by bornacheck** [comment]
**If there are any formatting issues here, it's probably because I'm new to GitHub.**

From the looks of the code, it seems the program is attempting to reference a variable which in some cases does not exist. On lines `21` thru `22` in the `try` block, the program creates a variable which is an integer adaptation of `input()`, and if there is no number or non-numerical chars, the program will instead just print "`Invalid input`" (or in your case, "`Invalid operand`"), but will never create the `number_1` and `number_2` variables. This means that lines `27` thru `55`, there are many references to both non-existent variables, thus giving an error. The IDE I am using, PyCharm Community highlights all the potential problems in the code. All of the yellow highlighted code is problematic code. Here's a screenshot.
![image](https://user-images.githubusercontent.com/85043913/155865058-581b2de7-4c25-4bec-8a08-0ffd5d14df6a.png)
The other piece of problematic code which is easier to fix is line `24` and line `25`. If the user types in an invalid input, all the program will do is print "`Invalid input`" (or in your case, "`Invalid operand`") and not create any kind of backup variable. Also, if the error occurs, the program can create some kind of variable to indicate that the error has or has not occurred, and if so, will skip calculation.
Here is the difference between the buggy code and the fixed code.
**Buggy:**
![image](https://user-images.githubusercontent.com/85043913/155865603-54c270b6-fbc3-44be-863b-e018d29911f4.png)
**Fixed:**
![image](https://user-images.githubusercontent.com/85043913/155865653-4f561019-6eb8-4d72-becd-841ce29b96fa.png)
If you would like all of the code, here is the fixed file itself. Although I can't provide it thru a `.py` file on GitHub, you can just copy/paste all the contents, rename it to a `.py` or just do whatever.
[calc.txt](https://github.com/airhead2048/python-calculator/files/8147860/calc.txt)
This is the output of the program:
![image](https://user-images.githubusercontent.com/85043913/155866260-8cd6a7b6-ce51-416a-9d3f-8f5235b9d920.png)

**Comment by aervnu** [comment]
> **If there are any formatting issues here, it's probably because I'm new to GitHub.**
> 
> From the looks of the code, it seems the program is attempting to reference a variable which in some cases does not exist. On lines `21` thru `22` in the `try` block, the program creates a variable which is an integer adaptation of `input()`, and if there is no number or non-numerical chars, the program will instead just print "`Invalid input`" (or in your case, "`Invalid operand`"), but will never create the `number_1` and `number_2` variables. This means that lines `27` thru `55`, there are many references to both non-existent variables, thus giving an error. The IDE I am using, PyCharm Community highlights all the potential problems in the code. All of the yellow highlighted code is problematic code. Here's a screenshot. ![image](https://user-images.githubusercontent.com/85043913/155865058-581b2de7-4c25-4bec-8a08-0ffd5d14df6a.png) The other piece of problematic code which is easier to fix is line `24` and line `25`. If the user types in an invalid input, all the program will do is print "`Invalid input`" (or in your case, "`Invalid operand`") and not create any kind of backup variable. Also, if the error occurs, the program can create some kind of variable to indicate that the error has or has not occurred, and if so, will skip calculation. Here is the difference between the buggy code and the fixed code. **Buggy:** ![image](https://user-images.githubusercontent.com/85043913/155865603-54c270b6-fbc3-44be-863b-e018d29911f4.png) **Fixed:** ![image](https://user-images.githubusercontent.com/85043913/155865653-4f561019-6eb8-4d72-becd-841ce29b96fa.png) If you would like all of the code, here is the fixed file itself. Although I can't provide it thru a `.py` file on GitHub, you can just copy/paste all the contents, rename it to a `.py` or just do whatever. [calc.txt](https://github.com/airhead2048/python-calculator/files/8147860/calc.txt) This is the output of the program: ![image](https://user-images.githubusercontent.com/85043913/155866260-8cd6a7b6-ce51-416a-9d3f-8f5235b9d920.png)

Many thanks to bornacheck for his solution to this issue! It'll now be closed. Version 1.5.1 is the approved version number of this patch.
The patched version of the executable will be available shortly.
